# Generated by Django 5.1.5 on 2025-02-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=255)),
                ('jenis', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='dokumen_pdfs/')),
                ('tanggal_unggah', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
