# Generated by Django 5.1.5 on 2025-02-04 16:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_surat', models.CharField(max_length=100, unique=True)),
                ('tanggal_surat', models.DateField()),
                ('irban', models.CharField(choices=[('IRBAN 1', 'IRBAN 1'), ('IRBAN 2', 'IRBAN 2'), ('IRBAN 3', 'IRBAN 3'), ('IRBAN 4', 'IRBAN 4'), ('IRBAN INVESTIGASI', 'IRBAN INVESTIGASI')], max_length=20)),
                ('tim_audit', models.JSONField(default=list)),
                ('uraian', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen/')),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_laporan', models.CharField(max_length=255)),
                ('tanggal_laporan', models.DateField(default=django.utils.timezone.now)),
                ('nomor_laporan', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='laporan/')),
                ('dokumen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='dokumen.dokumen')),
            ],
        ),
    ]
