# Generated by Django 5.1.5 on 2025-02-05 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumen',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-02-05 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dokumen',
            name='pengirim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
