# Generated by Django 5.1.5 on 2025-02-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dokumen',
            name='tanggal_unggah',
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='file',
            field=models.FileField(upload_to='dokumen/'),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='jenis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dokumen',
            name='nomor_surat',
            field=models.CharField(max_length=50),
        ),
    ]
