# Generated by Django 5.1.5 on 2025-02-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dokumen', '0002_dokumen_created_at_dokumen_pengirim'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dokumen',
            old_name='pengirim',
            new_name='user',
        ),
    ]
